Require pandas>=2.0
I got this error in 
`eegdash/dataset/registry.py:270`:
```
TypeError: NDFrame.infer_objects() got an unexpected keyword argument 'copy'
```
The copy parameter was introduced in pandas 2.0.0. See [release notes](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html)